# Generated by Django 3.2.2 on 2021-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210525_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descrip',
            field=models.TextField(max_length=5000000000000000000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
